CREATE DATABASE SpoofTest;
GO

USE SpoofTest;

CREATE TABLE Student
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Patronymic NVARCHAR(100) NOT NULL,
	[Group] NVARCHAR(20) NOT NULL,
	[Password] NVARCHAR(255) NOT NULL,
	[Login] NVARCHAR(100) NOT NULL CONSTRAINT UQ_Student_Login UNIQUE
);

CREATE TABLE Teacher
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Patronymic NVARCHAR(100) NOT NULL,
	[Password] NVARCHAR(255) NOT NULL,
	[Login] NVARCHAR(100) NOT NULL CONSTRAINT UQ_Teacher_Login UNIQUE
);

CREATE TABLE Test
(
	Id INT PRIMARY KEY IDENTITY,
	Title NVARCHAR(200) NOT NULL,
	LimitMinutes INT NOT NULL,
	TeacherId INT FOREIGN KEY REFERENCES Teacher(Id) NOT NULL,
);
GO

CREATE TABLE StudentTest
(
	StudentId INT FOREIGN KEY REFERENCES Student(Id) NOT NULL,
	TestId INT FOREIGN KEY REFERENCES Test(Id) NOT NULL,
	DeadLine DATETIME,
	Result DECIMAL(10, 2) NOT NULL,
	PRIMARY KEY(StudentId, TestId)
);

CREATE TABLE Question
(
	Id INT PRIMARY KEY IDENTITY,
	TestId INT FOREIGN KEY REFERENCES Test(Id) NOT NULL,
	IsOnce BIT,
	Title NVARCHAR(200) NOT NULL,
);
GO

CREATE TABLE Answer
(
	Id INT PRIMARY KEY IDENTITY,
	QuestionId INT FOREIGN KEY REFERENCES Question(Id) NOT NULL,
	Title NVARCHAR(200) NOT NULL,
	IsCorrect BIT,
);
GO

CREATE TABLE QuestionAnswer 
(
	StudentId INT NOT NULL,
	TestId INT NOT NULL,
	AnswerId INT FOREIGN KEY REFERENCES Answer(Id) NOT NULL,
	FOREIGN KEY(StudentId, TestId) REFERENCES StudentTest(StudentId, TestId),
	PRIMARY KEY(StudentId, TestId, AnswerId)
);