CREATE DATABASE SpoofTest;
GO

USE SpoofTest;

CREATE TABLE Test
(
	Id INT PRIMARY KEY IDENTITY,
	Title NVARCHAR(200) NOT NULL,
	LimitMinutes INT NOT NULL,
);
GO

CREATE TABLE Submitted
(
	Id INT PRIMARY KEY IDENTITY,
	TestId INT FOREIGN KEY REFERENCES Test(Id) NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Patronymic NVARCHAR(100) NOT NULL,
	SessionId NVARCHAR(100) NOT NULL,
	[Group] NVARCHAR(100) NOT NULL,
	Result DECIMAL(10,2) NOT NULL
);

CREATE TABLE Question
(
	Id INT PRIMARY KEY IDENTITY,
	TestId INT FOREIGN KEY REFERENCES Test(Id) NOT NULL,
	Title NVARCHAR(200) NOT NULL,
);
GO

CREATE TABLE Answer
(
	Id INT PRIMARY KEY IDENTITY,
	QuestionId INT FOREIGN KEY REFERENCES Question(Id) NOT NULL,
	Title NVARCHAR(200) NOT NULL,
	IsCorrect BIT,
);
GO

CREATE TABLE QuestionAnswer 
(
	SubmittedId INT FOREIGN KEY REFERENCES Submitted(Id) NOT NULL,
	AnswerId INT FOREIGN KEY REFERENCES Answer(Id) NOT NULL,
	PRIMARY KEY(SubmittedId, AnswerId)
);