CREATE DATABASE SpoofTest
GO

USE SpoofTest

CREATE TABLE [Group]
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(20) NOT NULL UNIQUE,
);

CREATE TABLE Teacher
(
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Patronymic NVARCHAR(100),
	[Login] NVARCHAR(100) NOT NULL UNIQUE,
	[Password] NVARCHAR(256) NOT NULL,
);
GO

CREATE TABLE Student
(
	Id INT PRIMARY KEY IDENTITY,
	GroupId INT FOREIGN KEY REFERENCES [Group](Id) NOT NULL,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Patronymic NVARCHAR(100),
	[Login] NVARCHAR(100) NOT NULL UNIQUE,
	[Password] NVARCHAR(256) NOT NULL,
);

CREATE TABLE Test
(
	Id INT PRIMARY KEY IDENTITY,
	TeacherpId INT FOREIGN KEY REFERENCES Teacher(Id) NOT NULL,
	Title NVARCHAR(100) NOT NULL,
	LimitMinutes INT NOT NULL DEFAULT 5 CHECK (LimitMinutes > 0),
	[Description] NVARCHAR(500), 
);
GO

CREATE TABLE Question
(
	Id INT PRIMARY KEY IDENTITY,
	TestId INT FOREIGN KEY REFERENCES Test(Id) NOT NULL,
	Content NVARCHAR(100) NOT NULL,
	IsOnce BIT NOT NULL,
);
GO

CREATE TABLE Answer
(
	Id INT PRIMARY KEY IDENTITY,
	QuestionId INT FOREIGN KEY REFERENCES Question(Id) NOT NULL,
	Content NVARCHAR(100) NOT NULL,
	IsCorrect BIT NOT NULL,
);

CREATE TABLE StudentTest
(
	Id INT PRIMARY KEY IDENTITY,
	StudentId INT FOREIGN KEY REFERENCES Student(Id) NOT NULL,
	TestId INT FOREIGN KEY REFERENCES Test(Id) NOT NULL,
	Result INT,
	AllPoints INT NOT NULL,
	Score INT CHECK(2 <= Score AND Score <= 5),
	SetDate DATETIME NOT NULL,
	PassDate DATETIME,
	CHECK(SetDate > PassDate),
	UNIQUE(StudentId, TestId),
);
GO

CREATE TABLE StudentAnswer
(
	Id INT CONSTRAINT PK_StudetAnswer_Id PRIMARY KEY IDENTITY,
	StudentTestId INT CONSTRAINT FK_StudetAnswer_StudentTestId FOREIGN KEY REFERENCES StudentTest(Id) NOT NULL,
	AnswerId INT CONSTRAINT FK_StudetAnswer_AnswerId FOREIGN KEY REFERENCES Answer(Id) NOT NULL,
);
